### ISSUE TITLE
目前代码貌似有些问题，有更新计划吗？

### ISSUE THREAD

**Issue by HADB** [Abriko/letsencrypt-alidns-hook#1]
今天试了下，目前代码已经跑不通了，dehydrated现在需要先执行--register --accept-terms，我加上之后，会有找不到hook.py的错误，修改了dockerfile中的WORKDIR /app/letsencrypt.sh目录后，还会再报如下的错误：
```
 + AliDNS hook executing: startup_hook
Traceback (most recent call last):
  File "hooks/alidns/hook.py", line 243, in <module>
    main(sys.argv[1:])
  File "hooks/alidns/hook.py", line 239, in main
    ops[argv[0]](argv[1:])
KeyError: 'startup_hook'
```

**Comment by abriko** [comment]
@HADB 有些困难，我现在没有域名在阿里云能测试了
